### PR TITLE
Making it read from xml file

### PR DESCRIPTION
**Pull request by rmetcalf9**
Hi,
The code now draws the diagram based on our test xml document.
I have had to add +@SuppressWarnings("restriction") to all my source to stop eclipse warning me on many lines of code. Let me know if there is a better solution.
Robert

### CODE REVIEW

**Comment by quiram** [comment]
Nice work :)
I'm guessing the next step will be to "bypass" the actual XML file, I mean, at the moment we can generate an object that represents the XML, maybe we can use that object directly as opposed to having to deserialise it. I expect to have some time on Friday, I can work on it then.

**Comment by rmetcalf9** [comment]
Yes, the code can be written to accept the JAXB object model (Root class), or the XML document, or an input stream or a web service call or all three depending on our requirement.
I have been considering how the application would run. It might be possible to have an option for it to run headless, specifying an output png file at the command line. That way it could be set to run on a webserver and simple generate the png file which is included in a webpage. It could then be triggered either by cron or by some part of the build process.

**Comment by quiram** [comment]
Yeah, that's good option if we want to show the same graph in multiple
displays. It wouldn't need to be running all the time, it could just do a
one-off run, generate the png and then die (and then the cron job will call
again later).

Otherwise, for a standalone application (ie, no web server or similar) I
think the best way is to make a JavaFX application with a Factory that
identifies the type of CI server and then generates the client; the
application would simply connect the drawing logic to the CiClient class to
obtain the data and re-run it every 30 seconds or so.


2015-09-15 11:49 GMT+01:00 rmetcalf9 <notifications@github.com>:

> Yes, the code can be written to accept the JAXB object model (Root class),
> or the XML document, or an input stream or a web service call or all three
> depending on our requirement.
> I have been considering how the application would run. It might be
> possible to have an option for it to run headless, specifying an output png
> file at the command line. That way it could be set to run on a webserver
> and simple generate the png file which is included in a webpage. It could
> then be triggered either by cron or by some part of the build process.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/quiram/build-hotspots/pull/7#issuecomment-140351130>.
>



-- 
Blogs: http://www.gatogordo.es/ -- http://www.FromFragileToAgile.com/
Twitter: @AbrahamMarin
LinkedIn: http://lnkd.in/TTHC8W

**Comment by quiram** [comment]
Hi Robert, is there a way I can contact you privately (meetup message or anything)?

**Comment by rmetcalf9** [comment]
Yes rmetcalf9@googlemail

**Comment by rmetcalf9** [comment]
Sorry forgot the .com rmetcalf9@googlemail.com

**Pull request merged**
