### PR TITLE
Adding prototype app with zoom and scroll code copied from another prj

### PR DESCRIPTION
**Pull request by rmetcalf9**
I have already got a JavaFX app where I have scrolling, zooming and saving a png screenshot already coded. The committed class contains that code and forms a prototype of the application.

### CODE REVIEW

**Comment by quiram** [comment]
Oh my, this is good :dancer:
I've started a DrawingBuilder that creates the XML object by querying the CI server, I think we'll be able to have working thing pretty soon :)

**Comment by quiram** [comment]
Just a check: it says that you've copied this code from another app, I'm assuming you own that other app, right? :)

**Comment by rmetcalf9** [comment]
Yes it's all my own code that I have written myself.

**Comment by rmetcalf9** [comment]
I realize that I am adjusting the size of the circle based on percentage not the colour. That should be easy to switch round.

**Comment by quiram** [comment]
Cool, thanks :)

**Pull request merged**
